# Generated by Django 4.1.3 on 2022-11-25 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chengji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolname', models.CharField(max_length=16, verbose_name='学校名称')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('nianji', models.CharField(max_length=16, verbose_name='年级')),
                ('banji', models.CharField(max_length=16, verbose_name='班级')),
                ('yuwen', models.FloatField(blank=True, null=True, verbose_name='语文')),
                ('shuxue', models.FloatField(blank=True, null=True, verbose_name='数学')),
                ('yingyu', models.FloatField(blank=True, null=True, verbose_name='英语')),
            ],
        ),
    ]
