# Generated by Django 4.1.3 on 2022-11-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_score', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nianji', models.SmallIntegerField(choices=[(1, '一年级'), (2, '二年级'), (3, '三年级'), (4, '四年级'), (5, '五年级'), (6, '六年级')], verbose_name='年级')),
                ('banji', models.SmallIntegerField(choices=[(1, '一班'), (2, '二班'), (3, '三班'), (4, '四班'), (5, '五班')], verbose_name='班级')),
                ('xueke', models.SmallIntegerField(choices=[(1, '语文'), (2, '数学'), (3, '英语')], verbose_name='语文任课教师')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
            ],
        ),
    ]
