# Generated by Django 4.1.3 on 2022-11-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_score', '0002_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='schoolname',
            field=models.CharField(default='jinji', max_length=16, verbose_name='学校名称'),
            preserve_default=False,
        ),
    ]
