# Generated by Django 4.1.3 on 2022-11-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_score', '0004_alter_teacher_banji_alter_teacher_nianji_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chengji',
            name='shuxue',
        ),
        migrations.RemoveField(
            model_name='chengji',
            name='yingyu',
        ),
        migrations.RemoveField(
            model_name='chengji',
            name='yuwen',
        ),
        migrations.AddField(
            model_name='chengji',
            name='defen',
            field=models.FloatField(blank=True, null=True, verbose_name='得分'),
        ),
        migrations.AddField(
            model_name='chengji',
            name='xueke',
            field=models.CharField(default='语文', max_length=16, verbose_name='学科'),
            preserve_default=False,
        ),
    ]
