# Generated by Django 4.1.4 on 2023-02-18 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_score', '0006_class_college_course_student_systemuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='college',
        ),
    ]
