# Generated by Django 4.1.4 on 2023-02-18 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_score', '0007_remove_class_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='grade',
            field=models.ForeignKey(help_text='所属年级', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_class', to='student_score.grade'),
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(help_text='名称', max_length=100, null=True),
        ),
    ]
