# Generated by Django 4.1.4 on 2023-02-18 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_score', '0008_alter_class_grade_alter_class_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='c_lass',
        ),
        migrations.RemoveField(
            model_name='course',
            name='college',
        ),
    ]
