# Generated by Django 4.1.4 on 2023-02-18 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sys_manage', '0006_power_rolepower'),
        ('student_score', '0009_remove_course_c_lass_remove_course_college'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chengji',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sys_manage.user'),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sys_manage.user'),
        ),
    ]
