# Generated by Django 4.1.3 on 2023-02-21 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_score', '0010_delete_chengji_delete_teacher_alter_student_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcoursemembership',
            name='college',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, to='student_score.college'),
            preserve_default=False,
        ),
    ]
