# Generated by Django 4.1.7 on 2024-05-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('request_method', models.CharField(max_length=200)),
                ('request_url', models.CharField(max_length=200)),
                ('ip', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'mon_montitor',
            },
        ),
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notify_type', models.CharField(max_length=200)),
                ('mail_from', models.CharField(max_length=200)),
                ('mail_to', models.CharField(max_length=200)),
                ('mail_content', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'mon_notify',
            },
        ),
    ]
